workspace:
  base: /go
  path: src/megpoid.xyz/go/drone-stack

pipeline:
  publish:
    image: plugins/docker
    repo: registry.megpoid.xyz/drone-stack
    registry: registry.megpoid.xyz
    tags: [ "latest"]
    secrets: [ docker_username, docker_password ]
    dockerfile: docker/Dockerfile
    when:
      branch: master
      event: push
